let USER=null,MASTERS={},ACTIVE_TAB='overview',READY=false,EPOCH=0;
const STATUS=['1. Đã tiếp nhận','2. Đang kiểm tra','3. Chờ báo giá','4. Chờ khách duyệt','5. Đang sửa','6. Chờ linh kiện','7. Đã sửa xong','8. Đã trả khách','9. Back lại khách','10. Bảo hành lại','11. Hủy sửa'];
const LOCATIONS=['Tại cửa hàng tiếp nhận','Đang chuyển đến kỹ thuật','Tại kỹ thuật','Đang chuyển về cửa hàng','Tại cửa hàng chờ trả','Đã trả khách'];
const PERIOD={year:new Date().getFullYear(),month:new Date().getMonth()+1};
const FILTERS={progress:{q:'',status:'',location:'',technician:'',page:1},repairs:{q:'',status:'',location:'',technician:'',page:1}};
const CACHE=new Map(),PENDING=new Map(),VIEWS=new Map(),TICKETS=new Map();const TTL=60000;
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function iso(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function bounds(){return {from:`${PERIOD.year}-${String(PERIOD.month||1).padStart(2,'0')}-01`,to:iso(new Date(PERIOD.year,PERIOD.month||12,0))};}
function statusCode(s){return Number((String(s||'').match(/^\s*(\d+)/)||[])[1]||0);}
function statusLabel(s){return STATUS[statusCode(s)-1]||s||'Chưa cập nhật';}
function jsArg(v){return esc(JSON.stringify(String(v||'')));}
function showToast(msg,type){const el=document.getElementById('toast');el.textContent=msg;el.className='toast show '+(type||'');setTimeout(()=>el.classList.remove('show'),3000);}
function invalidate(){EPOCH++;CACHE.clear();PENDING.clear();VIEWS.clear();TICKETS.forEach((v,k)=>TICKETS.set(k,v+1));}
function key(p){return JSON.stringify([USER&&USER.token,p]);}
function api(p){const read=['apiInfo','getMasters','operationsOverview','operationsList','getDetail'].includes(p.action),k=key(p),hit=CACHE.get(k);if(read&&hit&&Date.now()-hit.at<TTL)return Promise.resolve(hit.data);if(read&&PENDING.has(k))return PENDING.get(k);const epoch=EPOCH;
 const req=apiCall(p,{timeoutMs:45000}).then(r=>{if(!r||r.success===false)throw Error(r&&r.message||'Không tải được dữ liệu.');if(read&&epoch===EPOCH){CACHE.set(k,{at:Date.now(),data:r});if(CACHE.size>80)CACHE.delete(CACHE.keys().next().value);}if(!read)invalidate();return r;}).finally(()=>{if(PENDING.get(k)===req)PENDING.delete(k);});if(read)PENDING.set(k,req);return req;}
function payload(tab){return tab==='overview'?{action:'operationsOverview',...bounds()}:{action:'operationsList',...bounds(),...FILTERS[tab],onlyOutstanding:tab==='progress',limit:30};}
function periodPicker(){const years=[];for(let y=new Date().getFullYear();y>=2022;y--)years.push(y);document.getElementById('periodPicker').innerHTML=`<select id="periodYear" aria-label="Năm" onchange="changePeriod()">${years.map(y=>`<option value="${y}" ${y===PERIOD.year?'selected':''}>${y}</option>`).join('')}</select><select id="periodMonth" aria-label="Tháng" onchange="changePeriod()"><option value="0" ${!PERIOD.month?'selected':''}>Cả năm</option>${Array.from({length:12},(_,i)=>`<option value="${i+1}" ${PERIOD.month===i+1?'selected':''}>Tháng ${i+1}</option>`).join('')}</select>`;}
function changePeriod(){PERIOD.year=Number(document.getElementById('periodYear').value);PERIOD.month=Number(document.getElementById('periodMonth').value);Object.values(FILTERS).forEach(f=>f.page=1);invalidate();document.querySelectorAll('.ops-tab').forEach(el=>el.innerHTML='');return openTab(ACTIVE_TAB).then(warm);}
function warm(){
 const epoch=EPOCH,requests=['overview','progress','repairs'].filter(t=>t!==ACTIVE_TAB).map(payload),keys=requests.map(key),launched=Date.now();
 return apiCall({action:'dashboardBatch',requests},{timeoutMs:45000}).then(r=>{if(epoch!==EPOCH||!r||r.success===false)return;(r.data||[]).forEach((value,i)=>{const hit=CACHE.get(keys[i]);if(value&&value.success!==false&&(!hit||hit.at<launched))CACHE.set(keys[i],{at:Date.now(),data:value});});}).catch(e=>console.debug('Tải nền:',e.message));
}
function openTab(tab){if(!['overview','progress','repairs'].includes(tab))tab='overview';ACTIVE_TAB=tab;document.querySelectorAll('.ops-tab').forEach(el=>el.hidden=el.id!==tab);document.querySelectorAll('[data-tab]').forEach(el=>el.classList.toggle('active',el.dataset.tab===tab));document.getElementById('pageTitle').textContent={overview:'Theo dõi sửa chữa',progress:'Máy còn tồn',repairs:'Danh sách đơn'}[tab];if(!READY)return Promise.resolve();return loadTab(tab);}
function loadTab(tab){const el=document.getElementById(tab),p=payload(tab),k=key(p),view=VIEWS.get(tab),ticket=(TICKETS.get(tab)||0)+1;TICKETS.set(tab,ticket);if(view&&view.key===k&&Date.now()-view.at<TTL)return Promise.resolve();if(!view||view.key!==k)el.innerHTML=(tab==='overview'?'':filters(tab))+'<div class="ops-loading">Đang tải…</div>';return api(p).then(r=>{if(TICKETS.get(tab)!==ticket||key(payload(tab))!==k)return;el.innerHTML=tab==='overview'?overview(r.data||{}):listView(tab,r);VIEWS.set(tab,{key:k,at:Date.now()});}).catch(e=>{if(TICKETS.get(tab)===ticket)el.innerHTML=(tab==='overview'?'':filters(tab))+`<div class="ops-error">${esc(e.message)}<button onclick="refreshCurrent()">Thử lại</button></div>`;});}
function refreshCurrent(){invalidate();return openTab(ACTIVE_TAB);}
function overview(d){return `<div class="ops-kpis"><button onclick="jump('')"><strong>${d.pending||0}</strong><span>Máy còn tồn</span></button><button onclick="jump('7')"><strong>${d.ready||0}</strong><span>Sửa xong, chờ trả</span></button><button onclick="jump('overdue')"><strong>${d.overdue||0}</strong><span>Quá hẹn</span></button><button onclick="jump('unassigned')"><strong>${d.unassigned||0}</strong><span>Chưa gán thợ</span></button></div><div class="ops-section"><h2>Máy đang ở đâu?</h2><div class="ops-location-grid">${Object.entries(d.locations||{}).map(([loc,n])=>`<button onclick="jumpLocation(${jsArg(loc)})"><span>${esc(loc)}</span><b>${n}</b></button>`).join('')||'<p>Không còn máy tồn.</p>'}</div></div><div class="ops-section"><h2>Tiến độ xử lý</h2>${Object.entries(d.statuses||{}).sort((a,b)=>Number(a[0])-Number(b[0])).map(([code,n])=>`<button class="ops-status-row" onclick="jump(${jsArg(code)})"><span>${esc(STATUS[Number(code)-1]||'Chưa cập nhật')}</span><b>${n}</b></button>`).join('')||'<p>Không còn máy tồn.</p>'}</div>`;}
function jump(status){Object.assign(FILTERS.progress,{status,q:'',location:'',technician:'',page:1});return openTab('progress');}
function jumpLocation(location){Object.assign(FILTERS.progress,{status:'',q:'',location,technician:'',page:1});return openTab('progress');}
function filters(tab){const f=FILTERS[tab];return `<form class="ops-filters" onsubmit="applyFilters(event,${jsArg(tab)})"><div class="ops-search"><input name="q" aria-label="Tìm đơn" placeholder="Mã đơn, IMEI, SĐT, tên khách" value="${esc(f.q)}"><button type="submit">Tìm</button></div><div class="ops-filter-grid"><select name="status" aria-label="Trạng thái"><option value="">Tất cả trạng thái</option>${STATUS.map((s,i)=>`<option value="${i+1}" ${f.status===String(i+1)?'selected':''}>${esc(s)}</option>`).join('')}<option value="overdue" ${f.status==='overdue'?'selected':''}>Quá hẹn</option><option value="unassigned" ${f.status==='unassigned'?'selected':''}>Chưa gán thợ</option></select><select name="location" aria-label="Vị trí"><option value="">Tất cả vị trí</option>${LOCATIONS.concat('Chưa cập nhật').map(loc=>`<option ${f.location===loc?'selected':''}>${esc(loc)}</option>`).join('')}</select></div></form>`;}
function applyFilters(event,tab){event.preventDefault();const form=event.target;Object.assign(FILTERS[tab],{q:form.elements.q.value.trim(),status:form.elements.status.value,location:form.elements.location.value,page:1});return loadTab(tab);}
function listView(tab,r){const meta=r.meta||{},rows=r.data||[];return filters(tab)+`<div class="ops-count">${Number(meta.total||0).toLocaleString('vi-VN')} đơn</div>`+rows.map(card).join('')+(rows.length?'':'<div class="ops-empty">Không có đơn phù hợp.</div>')+(meta.pages>1?`<div class="ops-pager"><button ${meta.page<=1?'disabled':''} onclick="changePage(${jsArg(tab)},-1)">Trước</button><span>${meta.page}/${meta.pages}</span><button ${meta.page>=meta.pages?'disabled':''} onclick="changePage(${jsArg(tab)},1)">Sau</button></div>`:'');}
function changePage(tab,delta){FILTERS[tab].page+=delta;return loadTab(tab);}
function card(r){const id=jsArg(r.repairId),editable=USER.role!=='cskh',tech=['tech','tech_manager','department_head','admin'].includes(USER.role),closed=statusCode(r.status)===8||r.location==='Đã trả khách';return `<article class="ops-card"><div class="ops-card-head"><div><b>${esc(r.repairId)}</b><h3>${esc(r.product)}</h3></div><span class="ops-badge">${esc(statusLabel(r.status))}</span></div><div class="ops-position">${esc(r.location||'Chưa cập nhật vị trí')}</div><div class="ops-info"><span>Khách<b>${esc(r.customer||'—')}</b></span><span>Chi nhánh<b>${esc(r.branch||'—')}</b></span><span>Kỹ thuật<b>${esc(r.technician||'Chưa gán')}</b></span><span>Hẹn trả<b>${esc(dateOnly(r.appointment)||'—')}</b></span></div><p class="ops-service">${esc(r.repairService||r.request||'')}</p><div class="ops-actions"><button onclick="viewDetail(${id})">Chi tiết</button>${editable&&!closed?`<button onclick="editLocation(${id})">Bàn giao</button>`:''}${tech&&!closed?`<button class="primary" onclick="editStatus(${id})">Cập nhật</button>`:''}</div></article>`;}
function modal(title,body){document.getElementById('modalRoot').innerHTML=`<div class="ops-backdrop" onclick="if(event.target===this)closeModal()"><div class="ops-modal"><div class="ops-modal-head"><h2>${esc(title)}</h2><button onclick="closeModal()" aria-label="Đóng">×</button></div>${body}</div></div>`;document.body.classList.add('modal-open');}
function closeModal(){document.getElementById('modalRoot').innerHTML='';document.body.classList.remove('modal-open');}
function detail(id,render){modal('Đơn '+id,'<div class="ops-loading">Đang tải…</div>');const root=document.getElementById('modalRoot'),ticket=root.innerHTML;return api({action:'getDetail',repairId:id}).then(r=>{if(root.innerHTML!==ticket)return;render(r.data||{});}).catch(e=>{if(root.innerHTML===ticket)modal('Không tải được',`<p>${esc(e.message)}</p>`);});}
function viewDetail(id){return detail(id,r=>modal('Đơn '+id,`<div class="ops-detail">${[['Sản phẩm',r.product],['Khách hàng',r.customer],['Số điện thoại',r.phone],['IMEI',r.imei],['Chi nhánh nhận',r.branch],['Trạng thái',statusLabel(r.status)],['Vị trí máy',r.location||'Chưa cập nhật'],['Kỹ thuật',r.technician||'Chưa gán'],['Ngày nhận',dateOnly(r.date)],['Hẹn trả',dateOnly(r.appointment)],['Ngày sửa xong',dateOnly(r.completedDate)],['Ngày trả khách',dateOnly(r.handoverDate)],['Dịch vụ',r.repairService||r.request]].map(([label,v])=>`<div><span>${label}</span><b>${esc(v||'—')}</b></div>`).join('')}</div>`));}
function editLocation(id){return detail(id,r=>{let locations=LOCATIONS;if(USER.role==='store')locations=locations.filter(x=>['Tại cửa hàng tiếp nhận','Đang chuyển đến kỹ thuật','Tại cửa hàng chờ trả','Đã trả khách'].includes(x));if(USER.role==='tech')locations=locations.filter(x=>x!=='Đã trả khách');modal('Bàn giao máy',`<form class="ops-form" onsubmit="saveLocation(event,${jsArg(id)})"><label>Vị trí máy<select name="location"><option value="">Chọn vị trí thực tế</option>${locations.map(x=>`<option ${r.location===x?'selected':''}>${esc(x)}</option>`).join('')}</select></label><button class="primary" type="submit">Xác nhận</button><p class="ops-form-error" aria-live="polite"></p></form>`);});}
function editStatus(id){return detail(id,r=>modal('Cập nhật xử lý',`<form class="ops-form" onsubmit="saveStatus(event,${jsArg(id)})"><label>Trạng thái<select name="status">${STATUS.filter(x=>USER.role!=='tech'||!x.startsWith('8.')).map(x=>`<option ${statusCode(x)===statusCode(r.status)?'selected':''}>${esc(x)}</option>`).join('')}</select></label>${USER.role==='tech'?'':`<label>Kỹ thuật<select name="technician"><option value="">Chưa gán</option>${(MASTERS.kyThuat||[]).map(t=>`<option ${r.technician===t.name?'selected':''}>${esc(t.name)}</option>`).join('')}</select></label>`}<label>Dịch vụ sửa chữa<input name="service" value="${esc(r.repairService||'')}"></label><label>Kết quả kiểm tra / xử lý<textarea name="note">${esc(r.techNote||'')}</textarea></label><button class="primary" type="submit">Lưu cập nhật</button><p class="ops-form-error" aria-live="polite"></p></form>`));}
function saveForm(event,p){event.preventDefault();const form=event.target,button=form.querySelector('button[type="submit"]');button.disabled=true;return api(p).then(()=>{closeModal();showToast('Đã cập nhật');return refreshCurrent();}).catch(e=>{form.querySelector('.ops-form-error').textContent=e.message;}).finally(()=>button.disabled=false);}
function saveLocation(event,id){return saveForm(event,{action:'updateLocation',repairId:id,data:{location:event.target.elements.location.value}});}
function saveStatus(event,id){const f=event.target;return saveForm(event,{action:'updateStatus',repairId:id,data:{status:f.elements.status.value,technician:USER.role==='tech'?USER.name:f.elements.technician.value,repairService:f.elements.service.value,techNote:f.elements.note.value}});}
function initDashboard(){USER=requireLogin();if(!USER)return;document.getElementById('userName').textContent=USER.name||USER.username;document.getElementById('userRole').textContent=ROLE_LABELS[USER.role]||USER.role;periodPicker();openTab('overview');document.getElementById('overview').innerHTML='<div class="ops-loading">Đang tải…</div>';Promise.all([api({action:'apiInfo'}),api({action:'getMasters'})]).then(([info,masters])=>{if(info.version!==EXPECTED_API_VERSION||!info.operationsOnly)throw Error('Cần cập nhật Apps Script bản 16.0.');MASTERS=masters.data||{};READY=true;return openTab(ACTIVE_TAB);}).then(warm).catch(e=>{document.getElementById(ACTIVE_TAB).innerHTML=`<div class="ops-error">${esc(e.message)}</div>`;});}
document.addEventListener('DOMContentLoaded',initDashboard);
