let USER=null,MASTERS={},ACTIVE_TAB='overview',READY=false,EPOCH=0;
const STATUS=['1. Đã tiếp nhận','2. Đang kiểm tra','3. Chờ báo giá','4. Chờ khách duyệt','5. Đang sửa','6. Chờ linh kiện','7. Đã sửa xong','8. Đã trả khách','9. Back lại khách','10. Bảo hành lại','11. Hủy sửa'];
let BRANCHES=[];let FORCE_FRESH=false;
const PERIOD={year:new Date().getFullYear(),month:new Date().getMonth()+1};
const FILTERS={progress:{q:'',status:'',branch:'',technician:'',page:1},repairs:{q:'',status:'',branch:'',technician:'',page:1}};
const CACHE=new Map(),PENDING=new Map(),VIEWS=new Map(),TICKETS=new Map();const TTL=30000;
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function iso(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function bounds(){return {from:`${PERIOD.year}-${String(PERIOD.month||1).padStart(2,'0')}-01`,to:iso(new Date(PERIOD.year,PERIOD.month||12,0))};}
function statusCode(s){return Number((String(s||'').match(/^\s*(\d+)/)||[])[1]||0);}
function statusLabel(s){return STATUS[statusCode(s)-1]||s||'Chưa cập nhật';}
function jsArg(v){return esc(JSON.stringify(String(v||'')));}
function showToast(msg,type){const el=document.getElementById('toast');el.textContent=msg;el.className='toast show '+(type||'');setTimeout(()=>el.classList.remove('show'),3000);}
function invalidate(){EPOCH++;CACHE.clear();PENDING.clear();VIEWS.clear();TICKETS.forEach((v,k)=>TICKETS.set(k,v+1));}
function key(p){return JSON.stringify([USER&&USER.token,p]);}
function api(p){const read=['apiInfo','getMasters','operationsOverview','operationsList','getDetail'].includes(p.action),k=key(p),hit=CACHE.get(k);if(read&&hit&&Date.now()-hit.at<TTL)return Promise.resolve(hit.data);if(read&&PENDING.has(k))return PENDING.get(k);const epoch=EPOCH;
 const request=()=>apiCall(p,{timeoutMs:28000});
 const req=request().catch(err=>{if(!read||!(err.httpStatus===504||err.httpStatus===502||/API quá lâu|Failed to fetch|API HTTP 504/i.test(err.message)))throw err;return new Promise(resolve=>setTimeout(resolve,400)).then(request);}).then(r=>{if(!r||r.success===false)throw Error(r&&r.message||'Không tải được dữ liệu.');if(read&&epoch===EPOCH){CACHE.set(k,{at:Date.now(),data:r});if(CACHE.size>80)CACHE.delete(CACHE.keys().next().value);}if(!read)invalidate();return r;}).finally(()=>{if(PENDING.get(k)===req)PENDING.delete(k);});if(read)PENDING.set(k,req);return req;}
function payload(tab){return tab==='overview'?{action:'operationsOverview',...bounds()}:{action:'operationsList',...bounds(),...FILTERS[tab],onlyOutstanding:tab==='progress',limit:30};}
function periodPicker(){const years=[];for(let y=new Date().getFullYear();y>=2022;y--)years.push(y);document.getElementById('periodPicker').innerHTML=`<select id="periodYear" aria-label="Năm" onchange="changePeriod()">${years.map(y=>`<option value="${y}" ${y===PERIOD.year?'selected':''}>${y}</option>`).join('')}</select><select id="periodMonth" aria-label="Tháng" onchange="changePeriod()"><option value="0" ${!PERIOD.month?'selected':''}>Cả năm</option>${Array.from({length:12},(_,i)=>`<option value="${i+1}" ${PERIOD.month===i+1?'selected':''}>Tháng ${i+1}</option>`).join('')}</select>`;}
function changePeriod(){PERIOD.year=Number(document.getElementById('periodYear').value);PERIOD.month=Number(document.getElementById('periodMonth').value);Object.values(FILTERS).forEach(f=>{f.page=1;f.todayOnly=false;f.returnedTodayOnly=false;});invalidate();document.querySelectorAll('.ops-tab').forEach(el=>el.innerHTML='');return openTab(ACTIVE_TAB).then(warm);}
function warm(){
 const epoch=EPOCH,requests=['overview','progress','repairs'].filter(t=>t!==ACTIVE_TAB).map(payload),keys=requests.map(key),launched=Date.now();
 return apiCall({action:'dashboardBatch',requests},{timeoutMs:45000}).then(r=>{if(epoch!==EPOCH||!r||r.success===false)return;(r.data||[]).forEach((value,i)=>{const hit=CACHE.get(keys[i]);if(value&&value.success!==false&&(!hit||hit.at<launched))CACHE.set(keys[i],{at:Date.now(),data:value});});}).catch(e=>console.debug('Tải nền:',e.message));
}
function openTab(tab){if(!['overview','progress','repairs'].includes(tab))tab='overview';ACTIVE_TAB=tab;document.querySelectorAll('.ops-tab').forEach(el=>el.hidden=el.id!==tab);document.querySelectorAll('[data-tab]').forEach(el=>el.classList.toggle('active',el.dataset.tab===tab));document.getElementById('pageTitle').textContent={overview:'Theo dõi sửa chữa',progress:'Máy còn tồn',repairs:'Danh sách đơn'}[tab];if(!READY)return Promise.resolve();return loadTab(tab);}
function loadTab(tab){const el=document.getElementById(tab),p=payload(tab),k=key(p),view=VIEWS.get(tab),ticket=(TICKETS.get(tab)||0)+1;TICKETS.set(tab,ticket);if(view&&view.key===k&&Date.now()-view.at<TTL)return Promise.resolve();if(!view||view.key!==k)el.innerHTML=(tab==='overview'?'':filters(tab))+'<div class="ops-loading">Đang tải…</div>';const requestPayload=FORCE_FRESH?{...p,fresh:true}:p;FORCE_FRESH=false;return api(requestPayload).then(r=>{if(TICKETS.get(tab)!==ticket||key(payload(tab))!==k)return;if(tab==='overview')BRANCHES=(r.data||{}).branchOptions||[];else BRANCHES=Array.from(new Set(BRANCHES.concat(r.branchOptions||[])));el.innerHTML=tab==='overview'?overview(r.data||{}):listView(tab,r);VIEWS.set(tab,{key:k,at:Date.now()});}).catch(e=>{if(TICKETS.get(tab)===ticket)el.innerHTML=(tab==='overview'?'':filters(tab))+`<div class="ops-error">${esc(e.message)}<button onclick="refreshCurrent()">Thử lại</button></div>`;});}
function refreshCurrent(){invalidate();FORCE_FRESH=true;return openTab(ACTIVE_TAB);}
function overview(d){
 const groups=(rows,type)=>rows.map(r=>`<button class="ops-status-row" onclick="jumpGroup(${jsArg(type)},${jsArg(r.name)})"><span>${esc(r.name)}<small>${r.total} đơn trong kỳ</small></span><b>${r.pending} còn tồn</b></button>`).join('')||'<p>Chưa có đơn.</p>';
 return `<div class="ops-daily-head"><h2>Hôm nay</h2><span>${esc(d.todayLabel||'')}</span></div><div class="ops-kpis ops-daily"><button onclick="jumpToday('')"><strong>${d.receivedToday||0}</strong><span>Nhận hôm nay</span></button><button onclick="jumpReturnedToday()"><strong>${d.returnedToday||0}</strong><span>Trả hôm nay</span></button><button onclick="jump('')"><strong>${d.pending||0}</strong><span>Tổng máy còn tồn</span></button></div><div class="ops-today-pending">Trong số nhận hôm nay: <b>${d.receivedTodayPending||0}</b> đơn còn tồn</div><div class="ops-period-summary"><button onclick="jumpAwaitingStore()"><span>Chờ CH nhận</span><b>${d.waitingStore||0}</b></button><button onclick="jumpAll()"><span>Đơn trong kỳ</span><b>${d.periodTotal||0}</b></button><button onclick="jump('overdue')"><span>Máy quá hẹn</span><b>${d.overdue||0}</b></button></div><div class="ops-section"><h2>Đơn nhận hôm nay</h2>${Object.entries(d.todayStatuses||{}).sort((a,b)=>Number(a[0])-Number(b[0])).map(([code,n])=>`<button class="ops-status-row" onclick="jumpToday(${jsArg(code)})"><span>${esc(STATUS[Number(code)-1]||'Chưa cập nhật')}</span><b>${n}</b></button>`).join('')||'<p>Hôm nay chưa nhận đơn.</p>'}</div><div class="ops-section"><h2>Theo kỹ thuật</h2>${groups(d.technicians||[],'technician')}</div><div class="ops-section"><h2>Theo chi nhánh</h2>${groups(d.branches||[],'branch')}</div><div class="ops-section ops-late"><div class="ops-section-heading"><h2>Máy quá hẹn · ${d.overdue||0}</h2><button onclick="jump('overdue')">Xem tất cả</button></div>${(d.overdueRows||[]).map(card).join('')||'<p>Không có máy quá hẹn.</p>'}</div>`;
}
function resetFilters(tab){Object.assign(FILTERS[tab],{status:'',q:'',branch:'',technician:'',todayOnly:false,returnedTodayOnly:false,page:1});}
function jump(status){resetFilters('progress');FILTERS.progress.status=status;return openTab('progress');}
function jumpToday(status){resetFilters('repairs');FILTERS.repairs.status=status;FILTERS.repairs.todayOnly=true;return openTab('repairs');}
function jumpReturnedToday(){resetFilters('repairs');FILTERS.repairs.returnedTodayOnly=true;return openTab('repairs');}
function jumpAll(){resetFilters('repairs');return openTab('repairs');}
function jumpGroup(type,name){resetFilters('repairs');FILTERS.repairs[type]=name;return openTab('repairs');}

function filters(tab){const f=FILTERS[tab];return `<form class="ops-filters" onsubmit="applyFilters(event,${jsArg(tab)})"><div class="ops-search"><input name="q" aria-label="Tìm đơn" placeholder="IMEI, SĐT, tên khách" value="${esc(f.q)}"><button type="submit">Tìm</button></div><select name="branch" aria-label="Chi nhánh" onchange="applyFilters(event,${jsArg(tab)})"><option value="">Tất cả chi nhánh</option>${Array.from(new Set(BRANCHES.concat(f.branch?[f.branch]:[]))).map(b=>`<option ${f.branch===b?'selected':''}>${esc(b)}</option>`).join('')}</select></form>`;}
function statusChips(tab,r){
 const f=FILTERS[tab],counts=r.statusCounts||{},items=[['','Tất cả',r.totalBeforeStatus||0]].concat(STATUS.map((s,i)=>[String(i+1),s.replace(/^\d+\.\s*/,''),counts[i+1]||0]).filter((x,i)=>tab!=='progress'||i<7));
 items.push(['overdue','Quá hẹn',r.overdueCount||0],['unassigned','Chưa gán thợ',r.unassignedCount||0]);if(tab!=='progress')items.push(['waitingStore','Chờ CH nhận',r.waitingStoreCount||0]);
 return `<div class="ops-status-chips" aria-label="Lọc trạng thái">${items.map(([value,label,n])=>`<button class="ops-status-chip ${f.status===value?'active':''} ${value==='waitingStore'?'handover':''}" aria-pressed="${f.status===value}" onclick="chooseStatus(${jsArg(tab)},${jsArg(value)})"><span>${esc(label)}</span><b>${n}</b></button>`).join('')}</div>`;
}
function chooseStatus(tab,status){FILTERS[tab].status=status;FILTERS[tab].page=1;return loadTab(tab);}
function jumpAwaitingStore(){resetFilters('repairs');FILTERS.repairs.status='waitingStore';return openTab('repairs');}

function applyFilters(event,tab){event.preventDefault();const form=event.target.closest('form');Object.assign(FILTERS[tab],{q:form.elements.q.value.trim(),branch:form.elements.branch.value,technician:'',todayOnly:false,returnedTodayOnly:false,page:1});if(tab==='progress'&&FILTERS[tab].q){resetFilters('repairs');Object.assign(FILTERS.repairs,FILTERS[tab]);return openTab('repairs');}return loadTab(tab);}
function listView(tab,r){const meta=r.meta||{},rows=r.data||[];return filters(tab)+statusChips(tab,r)+`<div class="ops-count">${FILTERS[tab].status==='waitingStore'?'Chờ CH nhận · Tất cả các kỳ · ':tab==='progress'?'Máy còn tồn · Trạng thái 1–7 · ':r.searchAllHistory?'Toàn bộ lịch sử · ':FILTERS[tab].returnedTodayOnly?'Trả hôm nay · ':FILTERS[tab].todayOnly?'Nhận hôm nay · ':'Tất cả trạng thái trong kỳ · '}${Number(meta.total||0).toLocaleString('vi-VN')} đơn</div>`+rows.map(card).join('')+(rows.length?'':'<div class="ops-empty">Không có đơn phù hợp.</div>')+(meta.pages>1?`<div class="ops-pager"><button ${meta.page<=1?'disabled':''} onclick="changePage(${jsArg(tab)},-1)">Trước</button><span>${meta.page}/${meta.pages}</span><button ${meta.page>=meta.pages?'disabled':''} onclick="changePage(${jsArg(tab)},1)">Sau</button></div>`:'');}
function changePage(tab,delta){FILTERS[tab].page+=delta;return loadTab(tab);}
function quoteLabel(value){return value===''||value==null?'Chưa báo giá':fmtMoney(value);}
function card(r){
 const id=jsArg(r.repairId),role=USER.role,tech=['tech','tech_manager','department_head','admin'].includes(role),closed=[8,9,10,11].includes(statusCode(r.status)),t=r.tracking||{},canStore=['store','department_head','admin'].includes(role);
 return `<article class="ops-card"><div class="ops-branch">${esc(r.branch||'Chưa có chi nhánh')}</div><div class="ops-card-head"><div><b class="ops-imei-main">IMEI ${esc(r.imei||'Chưa có')}</b><h3>${esc(r.customer||'Chưa có tên khách')}</h3></div><span class="ops-badge">${esc(statusLabel(r.status))}</span></div><div class="ops-info"><span>Dòng máy<b>${esc(r.product||'—')}</b></span><span>Kỹ thuật<b>${esc(r.technician||'Chưa gán')}</b></span><span>Hẹn trả<b>${esc(dateOnly(r.appointment)||'—')}</b></span><span>Báo giá<b>${esc(quoteLabel(r.estimate))}</b></span></div><p class="ops-service">${esc(r.repairService||r.request||'Chưa có dịch vụ')}</p><div class="ops-receipts"><span>${t.techReceivedAt?'KT nhận':'KT chưa nhận'}</span><span>${t.storeReceivedAt?'CH nhận':'CH chưa nhận'}</span></div><div class="ops-actions"><button onclick="viewDetail(${id})">Chi tiết</button>${tech&&!closed&&!t.techReceivedAt?`<button onclick="confirmReceipt(${id},'techReceived')">KT nhận</button>`:''}${canStore&&!closed&&statusCode(r.status)===7&&!t.storeReceivedAt?`<button onclick="confirmReceipt(${id},'storeReceived')">CH nhận</button>`:''}${canStore&&!closed&&statusCode(r.status)===7&&t.storeReceivedAt?`<button onclick="confirmReturn(${id})">Cập nhật 8–11</button>`:''}${tech&&!closed?`<button class="primary" onclick="editStatus(${id})">Cập nhật</button>`:''}</div></article>`;
}

function modal(title,body){document.getElementById('modalRoot').innerHTML=`<div class="ops-backdrop" onclick="if(event.target===this)closeModal()"><div class="ops-modal"><div class="ops-modal-head"><h2>${esc(title)}</h2><button onclick="closeModal()" aria-label="Đóng">×</button></div>${body}</div></div>`;document.body.classList.add('modal-open');}
function closeModal(){document.getElementById('modalRoot').innerHTML='';document.body.classList.remove('modal-open');}
function detail(id,render){modal('Chi tiết máy','<div class="ops-loading">Đang tải…</div>');const root=document.getElementById('modalRoot'),ticket=root.innerHTML;return api({action:'getDetail',repairId:id}).then(r=>{if(root.innerHTML!==ticket)return;render(r.data||{},r);}).catch(e=>{if(root.innerHTML===ticket)modal('Không tải được',`<p>${esc(e.message)}</p>`);});}
function viewDetail(id){return detail(id,(r,full)=>{
 const t=r.tracking||{},canStore=['store','department_head','admin'].includes(USER.role),canInfo=['tech','tech_manager','department_head','admin'].includes(USER.role),canContact=['cskh','store','tech','tech_manager','department_head','admin'].includes(USER.role);
 const fields=[['Khách hàng',r.customer],['IMEI',r.imei],['Dòng máy',r.product],['Số điện thoại',r.phone],['Chi nhánh',r.branch],['Trạng thái',statusLabel(r.status)],['Kỹ thuật',r.technician||'Chưa gán'],['Ngày nhận',dateTime(r.date)],['Hẹn trả',dateTime(r.appointment)],['Dịch vụ',r.repairService||r.request],['Báo giá',quoteLabel(r.estimate)],['Ngày sửa xong',dateTime(r.completedDate)],['Ngày trả khách',dateTime(r.handoverDate)]];
 modal('IMEI '+(r.imei||'Chưa có'),`<div class="ops-detail">${fields.map(([label,v])=>`<div><span>${label}</span><b>${esc(v||'—')}</b></div>`).join('')}</div><div class="ops-detail-section"><h3>Xác nhận nhận máy</h3><p><b>KT nhận:</b> ${t.techReceivedAt?esc(t.techReceivedBy)+' · '+esc(dateTime(t.techReceivedAt)):'Chưa xác nhận'}</p><p><b>CH nhận:</b> ${t.storeReceivedAt?esc(t.storeReceivedBy)+' · '+esc(dateTime(t.storeReceivedAt)):'Chưa xác nhận'}</p>${canStore&&statusCode(r.status)===7&&!t.storeReceivedAt?`<button class="primary" onclick="confirmReceipt(${jsArg(id)},'storeReceived')">CH nhận</button>`:''}${canStore&&statusCode(r.status)===7&&t.storeReceivedAt?`<button class="primary" onclick="confirmReturn(${jsArg(id)})">Cập nhật 8–11</button>`:''}</div><div class="ops-detail-section"><h3>Thông tin báo khách</h3><p><b>Kết quả:</b> ${esc(t.customerResult||r.techNote||'Chưa cập nhật')}</p><p><b>Đang chờ:</b> ${esc(t.waitingReason||'—')}</p><p><b>Dự kiến hoàn tất:</b> ${esc(dateTime(t.expectedFinish)||'Chưa cập nhật')}</p>${canInfo&&statusCode(r.status)!==8?`<button onclick="editCustomerInfo(${jsArg(id)})">Cập nhật thông tin</button>`:''}</div><div class="ops-detail-section"><h3>Liên hệ khách</h3><p>${t.lastContactAt?esc(t.lastContactBy)+' · '+esc(dateTime(t.lastContactAt)):'Chưa ghi nhận lần báo khách'}</p><p>${esc(t.lastContactChannel||'')} ${esc(t.lastContactNote||'')}</p>${canContact?`<button onclick="editContact(${jsArg(id)})">Ghi nhận đã báo khách</button>`:''}</div><div class="ops-detail-section"><h3>Lịch sử đơn</h3>${(full.history||[]).map(h=>`<div class="ops-history"><small>${esc(dateTime(h.time))} · ${esc(h.user)}</small><b>${esc(h.action)}</b>${h.fromStatus||h.toStatus?`<p>${esc(statusLabel(h.fromStatus))} → ${esc(statusLabel(h.toStatus))}</p>`:''}<p>${esc(h.message)}</p></div>`).join('')||'<p>Chưa có lịch sử.</p>'}</div>${relatedHistory(full.relatedRepairs)}`);
 });}
function confirmReceipt(id,event){const title=event==='techReceived'?'KT nhận':'CH nhận';modal(title,`<p>Xác nhận bạn đã nhận máy thực tế?</p><form class="ops-form" onsubmit="saveForm(event,{action:'saveOpsTracking',repairId:${jsArg(id)},data:{event:${jsArg(event)}}})"><button class="primary" type="submit">Xác nhận đã nhận</button><p class="ops-form-error" aria-live="polite"></p></form>`);}
function editCustomerInfo(id){return detail(id,r=>{const t=r.tracking||{};modal('Thông tin để báo khách',`<form class="ops-form" onsubmit="saveCustomerInfo(event,${jsArg(id)})"><label>Kết quả kiểm tra ngắn gọn<textarea name="result">${esc(t.customerResult||'')}</textarea></label><label>Đang chờ việc gì<input name="waiting" value="${esc(t.waitingReason||'')}"></label><label>Dự kiến hoàn tất<input type="datetime-local" name="eta" value="${esc(String(t.expectedFinish||'').replace(' ','T').slice(0,16))}"></label><label>Báo giá (đ)<input name="quote" type="number" min="0" step="1000" value="${esc(r.estimate==null?'':r.estimate)}"></label><button class="primary" type="submit">Lưu thông tin</button><p class="ops-form-error" aria-live="polite"></p></form>`);});}
function saveCustomerInfo(event,id){const f=event.target;return saveForm(event,{action:'saveOpsTracking',repairId:id,data:{event:'customerInfo',customerResult:f.elements.result.value,waitingReason:f.elements.waiting.value,expectedFinish:f.elements.eta.value,estimate:f.elements.quote.value}});}
function editContact(id){modal('Ghi nhận báo khách',`<form class="ops-form" onsubmit="saveContact(event,${jsArg(id)})"><label>Kênh liên hệ<select name="channel"><option>Gọi điện</option><option>Zalo</option><option>Fanpage</option><option>Tại cửa hàng</option></select></label><label>Nội dung đã báo<textarea name="note" required></textarea></label><button class="primary" type="submit">Lưu ghi nhận</button><p class="ops-form-error" aria-live="polite"></p></form>`);}
function saveContact(event,id){return saveForm(event,{action:'saveOpsTracking',repairId:id,data:{event:'contact',channel:event.target.elements.channel.value,note:event.target.elements.note.value}});}

function confirmReturn(id){return detail(id,r=>{if(statusCode(r.status)!==7||!(r.tracking||{}).storeReceivedAt){modal('Chưa thể kết thúc','<p>Cần 7. Đã sửa xong và CH nhận trước khi cập nhật 8–11.</p>');return;}
 modal('Cập nhật 8–11',`<form class="ops-form" onsubmit="saveCompletion(event,${jsArg(id)})"><label>Trạng thái kết thúc<select name="status">${STATUS.slice(7).map(s=>`<option>${esc(s)}</option>`).join('')}</select></label><p>Chọn trạng thái đúng với kết quả bàn giao cho khách.</p><button class="primary" type="submit">Xác nhận cập nhật</button><p class="ops-form-error" aria-live="polite"></p></form>`);
});}
function saveCompletion(event,id){return saveForm(event,{action:'updateStatus',repairId:id,data:{status:event.target.elements.status.value}});}
function editableStatuses(r){return STATUS.filter(s=>{const n=statusCode(s);if(USER.role==='tech'&&n===8)return false;return n<8||s===r.status||(statusCode(r.status)===7&&(r.tracking||{}).storeReceivedAt);});}


function editStatus(id){return detail(id,(r,full)=>modal('Cập nhật xử lý',`<form class="ops-form" onsubmit="saveStatus(event,${jsArg(id)})"><label>Trạng thái<select name="status">${editableStatuses(r).map(x=>`<option ${statusCode(x)===statusCode(r.status)?'selected':''}>${esc(x)}</option>`).join('')}</select></label>${USER.role==='tech'?'':`<label>Kỹ thuật<select name="technician"><option value="">Chưa gán</option>${(MASTERS.kyThuat||[]).map(t=>`<option ${r.technician===t.name?'selected':''}>${esc(t.name)}</option>`).join('')}</select></label>`}${servicePicker(r,full)}<label>Kết quả xử lý để báo khách<textarea name="note">${esc(r.techNote||'')}</textarea></label><button class="primary" type="submit">Lưu cập nhật</button><p class="ops-form-error" aria-live="polite"></p></form>`));}
function saveForm(event,p){event.preventDefault();const form=event.target,button=form.querySelector('button[type="submit"]');button.disabled=true;return api(p).then(()=>{closeModal();showToast('Đã cập nhật');return refreshCurrent();}).catch(e=>{form.querySelector('.ops-form-error').textContent=e.message;}).finally(()=>button.disabled=false);}

function saveStatus(event,id){const f=event.target;return saveForm(event,{action:'updateStatus',repairId:id,data:{status:f.elements.status.value,technician:USER.role==='tech'?USER.name:f.elements.technician.value,services:Array.from(f.querySelectorAll('[name="services"]:checked')).map(x=>x.value),techNote:f.elements.note.value}});}
function initDashboard(){USER=requireLogin();if(!USER)return;document.getElementById('userName').textContent=USER.name||USER.username;document.getElementById('userRole').textContent=ROLE_LABELS[USER.role]||USER.role;periodPicker();openTab('overview');document.getElementById('overview').innerHTML='<div class="ops-loading">Đang tải…</div>';Promise.all([api({action:'apiInfo'}),api({action:'getMasters'})]).then(([info,masters])=>{if(info.version!==EXPECTED_API_VERSION||!info.operationsOnly||!info.monthlyOverview||!info.dailyHandover||!info.workflowTracking)throw Error('Cần cập nhật Apps Script bản 16.7.');MASTERS=masters.data||{};READY=true;return openTab(ACTIVE_TAB);}).then(warm).catch(e=>{document.getElementById(ACTIVE_TAB).innerHTML=`<div class="ops-error">${esc(e.message)}</div>`;});}
document.addEventListener('DOMContentLoaded',initDashboard);

function serviceNames(r,full){return (full.services&&full.services.length?full.services.map(x=>x.name):String(r.repairService||'').split(/[,;\n]+/)).map(x=>x.trim()).filter(Boolean);}
function servicePicker(r,full){
 const selected=serviceNames(r,full),names=Array.from(new Set(selected.concat((MASTERS.dichVu||[]).map(x=>x.name)).filter(Boolean)));
 return `<fieldset class="ops-services"><legend>Dịch vụ thực tế · chọn nhiều</legend><input type="search" placeholder="Tìm dịch vụ trong danh mục" aria-label="Tìm dịch vụ" oninput="filterServices(this)"><div class="ops-service-options">${names.map(name=>`<label data-service="${esc(name.toLocaleLowerCase('vi'))}"><input type="checkbox" name="services" value="${esc(name)}" ${selected.includes(name)?'checked':''}><span>${esc(name)}</span></label>`).join('')||'<p>Danh mục dịch vụ đang trống.</p>'}</div></fieldset>`;
}
function filterServices(input){const q=input.value.toLocaleLowerCase('vi').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d');input.closest('fieldset').querySelectorAll('[data-service]').forEach(el=>{el.hidden=!el.dataset.service.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').includes(q);});}
function relatedHistory(related){if(!related)return '';return [['machine','Lịch sử máy theo IMEI'],['customer','Lịch sử khách theo SĐT']].map(([key,title])=>{const h=related[key];return `<div class="ops-detail-section"><h3>${title}</h3>${!h?`<p>Chưa có ${key==='machine'?'IMEI':'SĐT'} để tra cứu.</p>`:`<p><b>${h.total} lần tiếp nhận${h.currentVisit?' · Đơn này là lần '+h.currentVisit:''}</b></p>${h.rows.map(r=>`<div class="ops-history"><small>Lần ${r.visit} · ${esc(dateTime(r.date)||'Chưa có ngày nhận')}${r.current?' · Đơn đang xem':''}</small><b>${esc(r.branch||'—')} · ${esc(statusLabel(r.status))}</b><p>${esc(r.customer||'—')} · ${esc(r.product||'—')} · IMEI ${esc(r.imei||'—')}</p><p>${esc(r.repairService||r.request||'Chưa có dịch vụ')} · ${esc(quoteLabel(r.estimate))}</p><p>Kỹ thuật: ${esc(r.technician||'Chưa gán')}${r.handoverDate?' · Trả khách: '+esc(dateTime(r.handoverDate)):''}</p>${r.result?`<p>Kết quả: ${esc(r.result)}</p>`:''}</div>`).join('')||'<p>Chưa có lịch sử.</p>'}`}</div>`;}).join('');}
